name: CD

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publishing ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [linux]
        include:
          - build_target: linux
            os: ubuntu-22.04
            artifact_suffix: linux-x86_64
            target: x86_64-unknown-linux-musl
            features: ''
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
          profile: minimal
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt update
          sudo apt install cmake g++ pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3 libncursesw5
          sudo apt install scdoc
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Document
        run: |
          cd extra/man
          ls -la
          for i in *; do scdoc < "${i}" > "${i/.scd}" && rm "${i}" || rm "${i}"; done
          ls -la
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Package
        shell: bash
        run: |
          cd target/
          ls -la
          cd release
          ls -la
          strip alacritty
          tar czvf alacritty-${{ matrix.target }}.tar.gz alacritty -C ../../extra man/
          shasum -a 256 alacritty-${{ matrix.target }}.tar.gz > alacritty-${{ matrix.target }}.sha256
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/alacritty-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
